### ISSUE TITLE
Q: trouble migrating

### ISSUE THREAD

**Issue by froggypaule** [ds-wizard/dsw2to3#3]
**The Question**
* ubuntu 20.04
* installed and ran dsw3 to create the postgress db
* installed 'pip install dsw2to3', but this that also required
    pip install wheel
    sudo apt install libpq-dev

* created config.yml (see attached)
* dry-run is troublesome (see attached as well)

![Screenshot from 2021-06-07 17-01-17](https://user-images.githubusercontent.com/47455219/121040327-1aa41880-c7b2-11eb-98b8-5a667c9170f1.png)
![Screenshot from 2021-06-07 16-59-49](https://user-images.githubusercontent.com/47455219/121040336-1bd54580-c7b2-11eb-9dd0-82c2866d8c6b.png)

**Comment by MarekSuchanek** [comment]
Thanks for the report... I will add the additional installation steps to the README and the TypeError is caused by me depending on Python 3.9+, I will fix that tomorrow morning and let you know here.

**Comment by MarekSuchanek** [comment]
@froggypaule I released 1.0.1, can you upgrade `pip install -U dsw2to3` and re-run? 

I also added CI, that checks it with Python versions 3.6, 3.7, 3.8, and 3.9.

**Comment by froggypaule** [comment]
thanks @MarekSuchanek!
* things are progressing and I have reached the stage of '--dry-run'
* but I am mystified: how can the dbs be found while all the docker instances are down? 

because of course, --dry-run can't find neither mongo nor postgres

`(env) paule@kame:~/ifb_sandbox/dsw/dsw2to3$ dsw2to3 -c ../dsw-deployment-example/config.yml --dry-run -l DEBUG
2021-06-08 09:11:28,791 |     INFO | Checking source database (MongoDB)
2021-06-08 09:11:58,944 | CRITICAL | - failed to check data in MongoDB (mongo:27017: [Errno -3] Temporary failure in name resolution, Timeout: 30s, Topology Description: <TopologyDescription id: 60bf18207a922f297705a773, topology_type: Single, servers: [<ServerDescription ('mongo', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('mongo:27017: [Errno -3] Temporary failure in name resolution')>]>)`

**Comment by MarekSuchanek** [comment]
You need to use hostnames that are accessible from the machine where you run the tool. Usually, you need to bind ports of databases to localhost and use localhost... see:

- https://github.com/ds-wizard/dsw2to3/blob/main/examples/docker-compose.yml#L76
- https://github.com/ds-wizard/dsw2to3/blob/main/examples/migration-config.yml#L4

(and similarly for PostgreSQL and Minio/S3)

You could run the tool from a docker container that can reach hostnames such as `mongo`, but I guess this is much easier way to do it.

**Comment by froggypaule** [comment]
(sorry, this could be a bug to be filled under dsw 3.0. but I don't know. Apologies also for the poor editing)

Hello @MarekSuchanek 

ok, I think I'll need personnalised help :( maybe this issue should appear elsewhere....

The story:
- to make sure I had my parametres all good etc, I 1) first ran DSW 2.14, then 2) DSW 3.00 (on a sandbox, no real data involved):
- dsw 2.14: all good, I certify that the data get's saved and restored in mongodb
- **dsw 3.00: actually, I discovered that I couldn't save anything in postgres** (yes, volumes are declared and we are talking about persistent data

so, for dsw 3.0:
- **I imported a km, it seems to have worked ok:**

dsw-server_1  | 2021-06-15T11:47:18.551008100Z [Info ] [I:ec6f8e90-2a91-49ec-aa3f-9eab2267fc66] [T:0d22599b-ee85-4860-ae23-59b636759057] [Database    ] Ensuring transaction
dsw-server_1  | 2021-06-15T11:47:18.551021148Z [Info ] [I:------------------------------------] [T:------------------------------------] [Database    ] INSERT INTO package VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)
dsw-server_1  | 2021-06-15T11:47:18.565610573Z [Info ] [I:ec6f8e90-2a91-49ec-aa3f-9eab2267fc66] [T:0d22599b-ee85-4860-ae23-59b636759057] [Database    ] Transaction commited
dsw-server_1  | 2021-06-15T11:47:18.565652959Z [Info ] [I:ec6f8e90-2a91-49ec-aa3f-9eab2267fc66] [T:0d22599b-ee85-4860-ae23-59b636759057] [API         ] 200 OK POST /packages/bundle
dsw-server_1  | 2021-06-15T11:47:18.618278156Z [Info ] [I:------------------------------------] [T:25686cbe-0c53-43a1-ae61-05d884a7dc89] [Database    ] Transaction started
dsw-server_1  | 2021-06-15T11:47:18.618574401Z [Info ] [I:------------------------------------] [T:25686cbe-0c53-43a1-ae61-05d884a7dc89] [Database    ] Transaction commited
dsw-server_1  | 2021-06-15T11:47:18.618606735Z [Info ] [I:ec6f8e90-2a91-49ec-aa3f-9eab2267fc66] [T:b88eb3fa-3755-4b8c-84e8-f8b79061a166] [Database    ] Transaction started
dsw-server_1  | 2021-06-15T11:47:18.618633069Z [Info ] [I:------------------------------------] [T:------------------------------------] [Database    ] SELECT COUNT(*)  FROM (SELECT COUNT(*)    FROM package    WHERE name ~* ?     GROUP BY organization_id, km_id) p
dsw-server_1  | 2021-06-15T11:47:18.619218042Z [Info ] [I:------------------------------------] [T:------------------------------------] [Database    ] SELECT * FROM package WHERE id IN (     SELECT CONCAT(organization_id, ':', km_id, ':', (max(string_to_array(version, '.')::int[]))[1] || '.' ||                                                     (max(string_to_array(version, '.')::int[]))[2] || '.' ||                                                     (max(string_to_array(version, '.')::int[]))[3])     FROM package     WHERE name ~* ?      GROUP BY organization_id, km_id ) ORDER BY name asc  offset 0 limit 20
dsw-server_1  | 2021-06-15T11:47:18.627777884Z [Info ] [I:------------------------------------] [T:------------------------------------] [Database    ] SELECT version FROM package WHERE organization_id = ? and km_id = ?
dsw-server_1  | 2021-06-15T11:47:18.628327284Z [Info ] [I:ec6f8e90-2a91-49ec-aa3f-9eab2267fc66] [T:b88eb3fa-3755-4b8c-84e8-f8b79061a166] [Database    ] Ensuring transaction


- **but then, after restarting dsw 3.0**, everything is lost; inspection of docker volumes doesn't show anything in particular;
but I notice this:

postgres_1    | 2021-06-15T11:46:13.027462709Z 2021-06-15 11:46:13.027 UTC [47] LOG:  database system is shut down
postgres_1    | 2021-06-15T11:46:13.116837747Z  done
postgres_1    | 2021-06-15T11:46:13.116857436Z server stopped
postgres_1    | 2021-06-15T11:46:13.117004628Z 
postgres_1    | 2021-06-15T11:46:13.117014236Z PostgreSQL init process complete; ready for start up.
postgres_1    | 2021-06-15T11:46:13.117016654Z 
postgres_1    | 2021-06-15T11:46:13.131646188Z 2021-06-15 11:46:13.131 UTC [1] LOG:  starting PostgreSQL 13.2 (Debian 13.2-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
postgres_1    | 2021-06-15T11:46:13.131760331Z 2021-06-15 11:46:13.131 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1    | 2021-06-15T11:46:13.131778607Z 2021-06-15 11:46:13.131 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1    | 2021-06-15T11:46:13.135348916Z 2021-06-15 11:46:13.135 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1    | 2021-06-15T11:46:13.139402659Z 2021-06-15 11:46:13.139 UTC [75] LOG:  database system was shut down at 2021-06-15 11:46:13 UTC
postgres_1    | 2021-06-15T11:46:13.142728780Z 2021-06-15 11:46:13.142 UTC [1] LOG:  database system is ready to accept connections
postgres_1    | 2021-06-15T11:46:13.348610898Z 2021-06-15 11:46:13.348 UTC [82] ERROR:  relation "document_queue" does not exist at character 15
postgres_1    | 2021-06-15T11:46:13.348624541Z 2021-06-15 11:46:13.348 UTC [82] STATEMENT:  SELECT * FROM document_queue;
postgres_1    | 2021-06-15T11:46:13.556096235Z 2021-06-15 11:46:13.555 UTC [83] ERROR:  relation "document_queue" does not exist at character 15
postgres_1    | 2021-06-15T11:46:13.556129974Z 2021-06-15 11:46:13.555 UTC [83] STATEMENT:  SELECT * FROM document_queue;
postgres_1    | 2021-06-15T11:46:13.963983762Z 2021-06-15 11:46:13.963 UTC [84] ERROR:  relation "document_queue" does not exist at character 15
postgres_1    | 2021-06-15T11:46:13.964012977Z 2021-06-15 11:46:13.963 UTC [84] STATEMENT:  SELECT * FROM document_queue;
postgres_1    | 2021-06-15T11:46:14.767945098Z 2021-06-15 11:46:14.767 UTC [86] ERROR:  relation "document_queue" does not exist at character 15
postgres_1    | 2021-06-15T11:46:14.767961665Z 2021-06-15 11:46:14.767 UTC [86] 





finally I post here the **docker-compose file for dsw 3.0 j**ust in case. 
version: '3'
services:

  dsw-server:
    image: datastewardshipwizard/wizard-server:3.0.0
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - minio
    volumes:
      - ./dsw.yml:/application/engine-wizard/config/application.yml:ro

  dsw-client:
    image: datastewardshipwizard/wizard-client:3.0.0
    restart: always
    ports:
      - 8086:80
    environment:
      API_URL: http://localhost:3000

  docworker:
    image: datastewardshipwizard/document-worker:3.0.0
    restart: always
    depends_on:
      - postgres
      - minio
      - dsw-server
    volumes:
      - ./dsw.yml:/app/config.yml:ro

  postgres:
    image: postgres:13.2
    restart: always
    # (!) Expose only for debugging locally or set-up authentication
    # ports:
    #   - 127.0.0.1:15432:5432
    environment:
      POSTGRES_DB: engine-wizard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # (!) Mount for persistent data
    volumes:
     - db-data:/data/db
    # OR
    #  - ./db-data/data:/data/db

  minio:
    image: minio/minio:RELEASE.2021-05-27T22-06-31Z
    command: server /data
    # (!) Expose only for debugging locally or set-up authentication
    # ports:
    #   - 127.0.0.1:19000:9000
    # (!) Mount and backup for persistent data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minioPassword
    # (!) Mount for persistent data
    volumes:
      - s3-data:/data
    # OR
    #  - ./s3-data/data:/data

volumes:
   db-data:
   s3-data:


Thanks!

**Comment by froggypaule** [comment]
to be complete wrt the previous post, here is dsw.yml


general:
  clientUrl: http://localhost:8086
  secret: b7zFNUhFYIFLmDSFKFkp0Bnp8Z3uWGnH
  serviceToken: NlQSNbGvh7EtcpinGnHE9g91

database:
  connectionString: postgresql://postgres:postgres@postgres:5432/engine-wizard

s3:
  url: http://minio:9000
  username: minio
  password: minioPassword
  bucket: engine-wizard

mail:
  enabled: false
  name:
  email:
  host:
  port:
  ssl:
  authEnabled:
  username:
  password:

**Comment by MarekSuchanek** [comment]
Hello, not sure what do you mean by "sandbox" and how you could not save any data? What was it showing? How are you restarting it?

You should:

1. Run 2.14 with MongoDB and RabbitMQ
2. Change docker-compose to use 3.0 and PostgreSQL + S3
3. `docker-compose down`
4. `docker-compose up -d`
5. Now DSW 3.0 is usable but with only default data, you can create new "from fresh"
6. To migrate, run `dsw2to3 -d -c <your-config.yml>` and then `dsw2to3 -c <your-config.yml>`

**Comment by froggypaule** [comment]
Hello @MarekSuchanek .
And yes but I am still struggling; I see what you are getting at, but no such luck yet.
First things first, I post a bug wrt to DSW 3.0 not being able to save data.

**Comment by froggypaule** [comment]
Ok, I managed to do a migration. Later I'll rewrite the migration steps the way I understood the process. But for now, I am a bit worried.

Attached here is a a snippet of the sort or error messages I got. Migration seem to have gone well, but these integrity issues worry me.
[pbs_migration.txt](https://github.com/ds-wizard/dsw2to3/files/6677724/pbs_migration.txt)

**Comment by froggypaule** [comment]
Dear @MarekSuchanek 

Well, I found this migration process difficult; not being a docker native --far from it-- it took me ages to get my head around it.
But, here is what I would suggest as a step-wise solution:

Note: this assumes one is running dsw on docker; not sure how to do this otherwise.

1. one assumes that dsw 2.x is running
2. shut dsw 2.x down:  `docker-compose down`
3. suppose that docker-compose-3.yml and dsw.yml are the files describing dsw 3.0.0  (needs an example file here);
    run dsw 3.0.0 with `docker-compose -f docker-compose-3.yml up -d`
    this will initiate the s3 + postgres database
4. shut down dsw 3.0.0  `docker-compose -f docker-compose-3.yml down`
5. modify the docker-compose.yml file that describes your current dsw 2.x version 
    5.1 to add the services postgres and minio (give example) 
          without forgetting to expose the ports (as well as exposing  the ports for mongo)
    5.2 and modify the depends_on flag for dsw_server to include minio and postgres
6. run dsw 2.x with this configuration 
7. install dsw2to3 as follows:
    sudo apt install libpq-dev
    sudo apt-get install python3-venv
    python3 -m venv env
    . env/bin/activate
    pip install wheel
    pip install dsw2to3
8. ensure that config.yml matches the configuration in the currently running dsw 2.x (but don't forget to set the host as localhost if running locally, or an IP address if running remotely)
9. effect the migration
    9.1 first a dry run `dsw2to3 -c config.example.yml --dry-run`
         (possibly with --fix-integrity  ??)
    9.2 then the migration itself `dsw2to3 -c config.example.yml`
10. shut down dsw 2.x
11. run dsw 3.0 again: the migration has succeded    


    
So I find this quite intricate; possibly this is because my handle of docker is minimal....  ;) 
You'll let me know your thoughts....

**Comment by MarekSuchanek** [comment]
Steps 5, 6, 10 are not necessary... in step 3, you can either create a new docker-compose.yml for DSW 3.0 or adjust the existing one (add S3 + Postgres, delete/comment out MongoDB/RabbitMQ, and change versions of DSW). But happy to hear that migration has succeeded!

**Comment by froggypaule** [comment]
.... mummm.... let me ask a question:  to get the migration working, one has to have the mongo and minio + postgres up and running isn't it?
well, I am puzzled

**Comment by froggypaule** [comment]
More importantly, do you have any thoughts re the integrity issues I mentioned here (https://github.com/ds-wizard/dsw2to3/issues/3#issuecomment-864090778)?
Thanks!

**Comment by MarekSuchanek** [comment]
> .... mummm.... let me ask a question: to get the migration working, one has to have the mongo and minio + postgres up and running isn't it?
> well, I am puzzled

Sure, sorry... comment/delete Mongo in docker-compose.yml after the migration.

> More importantly, do you have any thoughts re the integrity issues I mentioned here (#3 (comment))?
> Thanks!

* Those with `ActionKey` are totally OK (its basically a junk somehow left in DB).
* The one with Package is really strange as this should not happen by any way from DSW UI, maybe you did some changes in UI/JSONs? But if you don't need `IFB:BiGEst-PGD-Structure-test:0.0.1` then it is OK. If you need it, then you have to fix it in MongoDB before executing the data migration...
* The one with Branch is caused by the one with Package (as it leaves out `IFB:BiGEst-PGD-Structure-test:0.0.1`, it must leave out also its KM Editor).

**Comment by froggypaule** [comment]
Ok, I am glad :)  (that to access mongo, the container has to be up and running ...  ;)  )
And thanks for the answers re data integrity. 

At last... I'll close this ticket. :)
